master:
  image: "jenkins/jenkins"
  tag: "lts"
  serviceType: ClusterIP
  installPlugins:
    - credentials-binding
    - cucumber-reports
    - embeddable-build-status
    - ghprb
    - git
    - junit
    - kubernetes
    - workflow-aggregator
    - workflow-job
persistence: 
  enabled: true
  storageClass: jelastic-dynamic-volume
ingress:
  enabled: true
  apiVersion: "networking.k8s.io/v1beta1"
  labels: {}
  annotations: { kubernetes.io/ingress.class: nginx, nginx.ingress.kubernetes.io/ssl-redirect: 'false' }
  path: "/jenkins"
  # configures the hostname e.g. jenkins.example.com
  hostName:
  tls:
  # - secretName: jenkins.cluster.local
  #   hosts:
  #     - jenkins.cluster.local