master:
  image: jenkins/jenkins
  tag: lts
  serviceType: ClusterIP
  installPlugins:
    - credentials-binding
    - cucumber-reports
    - embeddable-build-status
    - ghprb
    - git
    - junit
    - kubernetes
    - workflow-aggregator
    - workflow-job
  jenkinsUriPrefix: /ci
persistence: 
  enabled: true
  storageClass: jelastic-dynamic-volume
ingress:
  enabled: true
  apiVersion: extensions/v1beta1
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/ssl-redirect: 'false'
  path: /ci