master:
  image: jenkins/jenkins
  tag: lts
  serviceType: ClusterIP
  installPlugins:
    - credentials-binding
    - cucumber-reports
    - embeddable-build-status
    - ghprb
    - git
    - junit
    - kubernetes
    - workflow-aggregator
    - workflow-job
  # this parameter can be set instead of the ingress.kubernetes.io/rewrite-target annotation
  jenkinsUriPrefix: /ci
  ingress:
    enabled: true
    apiVersion: extensions/v1beta1
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
      # this parameter can be set instead of jenkinsUriPrefix
      # nginx.ingress.kubernetes.io/rewrite-target: /$2
    path: /ci
    # hostName: ci.env-8958284.hidora.com
persistence: 
  enabled: true
  storageClass: jelastic-dynamic-volume