master:
  image: "jenkins/jenkins"
  tag: "lts"
  serviceType: ClusterIP
  installPlugins:
    - credentials-binding
    - cucumber-reports
    - embeddable-build-status
    - ghprb
    - git
    - junit
    - kubernetes
    - workflow-aggregator
    - workflow-job
persistence: 
  enabled: true
  storageClass: jelastic-dynamic-volume