apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-ui
  labels:
    app: admin-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-ui
    spec:
      containers:
      - image: abiosoft/caddy:latest
        name: admin-ui
        volumeMounts:
          - mountPath: /etc/Caddyfile # mount caddy-conf volume to /etc
            subPath: Caddyfile
            readOnly: true 
            name: caddy-conf
          - mountPath: /srv
            name: pvc-45ed40b8-5561-439a-b86b-32196c89d12c
        resources:
          limits:
            cpu: 150m
            memory: 250Mi
      volumes:
        - name: caddy-conf
          configMap:
            name: caddy-conf # place ConfigMap `caddy-conf` on /etc
            items:
              - key: Caddyfile
                path: Caddyfile
          # this name can be retrieved by getting the persistent volume claim's volumeName in its spec after installation (the name is generated automatically)
        - name: pvc-45ed40b8-5561-439a-b86b-32196c89d12c
          persistentVolumeClaim: 
            claimName: admin-ui