kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: admin-ui
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: jelastic-dynamic-volume
  volumeMode: Filesystem