kind: Service
apiVersion: v1
metadata:
  name: admin-ui
  namespace: default
  labels:
    app: admin-ui
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: admin-ui
  type: ClusterIP
